config/routes.rb
Rails.application.routes.draw do
  get 'sources/_new'

  get 'helplinks/_new'

  get 'temas/_new'

  get 'home' => 'welcome#index'
  post '/' => 'welcome#index'

  get 'sessions/new'
  get 'users' => 'users#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#_new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'edit' => 'users#edit'
  
  resources :users
  mount Ckeditor::Engine => '/ckeditor'
  resources :courses
  resources :courses do
    resources :lessons
  end
  resources :courses do
    resources :temas
  end
  resources :courses do
    resources :helplinks
  end
  resources :courses do
    resources :sources
  end
  root "welcome#index"

  get '*path' => redirect('/')

end

app/views/layouts/_alerts.html.erb
<!-- Alerts -->
<div class="site-alerts">
	<div class="container">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %> alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<%= message %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_modal_login.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="login">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h2 class="modal-title">¡Bienvenido de vuelta!</h2>
			</div>
			<div class="modal-body">
				<%=render "/sessions/new"%>
<!-- 				<hr>
				<h3>Conéctate con alguna red social</h3>
				<ul class="social-connect">
					<li class="btn-facebook">
						<a href="">
							<img src="/assets/facebook.svg">
							<p>Facebook</p>
						</a>
					</li>
					<li class="btn-googleplus">
						<a href="">
							<img src="/assets/google.svg">
							<p>Google</p>
						</a>
					</li>
				</ul> -->
			</div>
		</div>
	</div>
</div>

app/views/layouts/_modal_signup.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="signup">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h2 class="modal-title">¡Únete a nosotros!</h2>
			</div>
			<div class="modal-body">
				<%=render "/users/new"%>
<!-- 				<hr>
				<h3>Conéctate con alguna red social</h3>
				<ul class="social-connect">
					<li class="btn-facebook">
						<a href="">
							<img src="/assets/facebook.svg">
							<p>Facebook</p>
						</a>
					</li>
					<li class="btn-googleplus">
						<a href="">
							<img src="/assets/google.svg">
							<p>Google</p>
						</a>
					</li>
				</ul> -->
			</div>
		</div>
	</div>
</div>

app/views/layouts/_site_footer.html.erb
<footer class="site-footer">
	<div class="container">
		<ul class="list-unstyled">
			<li>
				<a href="">
					<strong>Fizcode</strong>
				</a>
			</li>
			<li>
				<a href="">
					&copy; Copyright 2015
				</a>
			</li>
			<li>
				<a href="">
					Aviso Legal
				</a>
			</li>
			<li>
				<a href="">
					Contacto
				</a>
			</li>
			<li>
				<a href="">
					Blog
				</a>
			</li>
		</ul>
	</div>
</footer>

app/views/layouts/_site_header.html.erb
<header class="site-header">
	<nav class="navbar">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to image_tag("/assets/logo.svg", class: "logo"), root_url, class: "navbar-brand" %>
			</div>
			<div class="collapse navbar-collapse" id="collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li><a class="btn-login" data-toggle="modal" data-target="#login">Iniciar Sesión</a></li>
					<li><a class="btn btn-orange btn-lg btn-signup" data-toggle="modal" data-target="#signup">Registrarse</a></li>
				</ul>
			</div>
		</div>
	</nav>
</header>

app/views/layouts/_site_header_logged.html.erb
<header class="site-header">
	<nav class="navbar">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to image_tag("/assets/logo.svg", class: "logo"), root_url, class: "navbar-brand" %>
			</div>
			<div class="collapse navbar-collapse" id="collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						<!-- <span class="glyphicon glyphicon-user"></span>  -->
						<span><%= current_user.name%></span>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "Configuración", edit_user_path(current_user)%></li>
						<li role="separator" class="divider"></li>
						<li><%= link_to "Salir", logout_path, method: "delete"%></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>fizcode</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Lato Font -->
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,400italic' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in?%>
  <%=render "/layouts/site_header_logged"%>
<%else%>
  <%=render "/layouts/site_header"%>
<%end%>

<main class="site-main">
<%=render "/layouts/alerts"%>
<%= yield %>
</main>

<%=render "/layouts/site_footer"%>
<% if !logged_in?%>
	<%=render "/layouts/modal_login"%>
	<%=render "/layouts/modal_signup"%>
<%end%>
</body>
</html>